version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    open-pull-requests-limit: 10
    groups:
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "vite-plugin-*"
      vue:
        patterns:
          - "vue"
          - "@vue/*"
          - "@vueuse/*"
          - "vue-tsc"
          - "pinia"
          - "primevue"
          - "primeflex"
      semantic-release:
        patterns:
          - "semantic-release"
          - "@semantic-release/*"
          - "conventional-changelog-*"

  - package-ecosystem: pub
    directory: /packages/showrunner-flutter
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
