compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@types/send@*":
    dependencies:
      mime: "1.6.0"
  "@vitejs/plugin-vue@^5":
    peerDependencies:
      vite: ^5.0.0 || ^6.0.0 || ^7.0.0

logFilters:
  - code: YN0060
    level: discard

yarnPath: .yarn/releases/yarn-4.1.0.cjs
