const PLUGIN_ICON_FALLBACKS: Record<string, string> = {
	ShowRunner: "mdi mdi-run-fast",
	advss: "mdi mdi-application-brackets-outline",
	aitum: "mdi mdi-vector-link",
	bluesky: "mdi mdi-cloud-outline",
	dashboards: "mdi mdi-view-dashboard-outline",
	discord: "mdi mdi-discord",
	donordrive: "mdi mdi-hand-heart-outline",
	elgato: "mdi mdi-keyboard-outline",
	govee: "mdi mdi-led-strip-variant",
	http: "mdi mdi-web",
	input: "mdi mdi-keyboard",
	iot: "mdi mdi-chip",
	lifx: "mdi mdi-lightbulb-on-outline",
	minecraft: "mdi mdi-cube-outline",
	moderation: "mdi mdi-shield-check",
	obs: "obsi obsi-obs obs-blue",
	os: "mdi mdi-monitor",
	overlays: "mdi mdi-layers-outline",
	"philips-hue": "mdi mdi-lightbulb-group-outline",
	random: "mdi mdi-dice-multiple-outline",
	remote: "mdi mdi-remote",
	sound: "mdi mdi-volume-high",
	spellcast: "mdi mdi-auto-fix",
	"stream-plans": "mdi mdi-calendar-clock",
	time: "mdi mdi-clock-outline",
	"tplink-kasa": "mdi mdi-power-socket",
	twinkly: "mdi mdi-string-lights",
	twitch: "mdi mdi-twitch twitch-purple",
	variables: "mdi mdi-variable",
	voicemod: "mdi mdi-microphone-variant",
	wyze: "mdi mdi-cctv",
	youtube: "mdi mdi-youtube youtube-red",
}

export function pluginIcon(pluginId: string, icon?: string) {
	return icon || PLUGIN_ICON_FALLBACKS[pluginId] || "mdi mdi-puzzle-outline"
}
