import 'package:flutter/services.dart';

const legacyKeyboardKeyNames = <String>[
  'Space',
  'Escape',
  'Tab',
  'LeftAlt',
  'LeftControl',
  'RightAlt',
  'RightControl',
  'LeftShift',
  'RightShift',
  'F1',
  'F2',
  'F3',
  'F4',
  'F5',
  'F6',
  'F7',
  'F8',
  'F9',
  'F10',
  'F11',
  'F12',
  'F13',
  'F14',
  'F15',
  'F16',
  'F17',
  'F18',
  'F19',
  'F20',
  'F21',
  'F22',
  'F23',
  'F24',
  '0',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
  'Minus',
  'Equals',
  'Backspace',
  'LeftBracket',
  'RightBracket',
  'Backslash',
  'Semicolon',
  'Quote',
  'Enter',
  'Comma',
  'Period',
  'Slash',
  'Left',
  'Up',
  'Right',
  'Down',
  'PrintScreen',
  'Pause',
  'Insert',
  'Delete',
  'Home',
  'End',
  'PageUp',
  'PageDown',
  'Add',
  'Subtract',
  'Multiply',
  'Divide',
  'Decimal',
  'NumPad0',
  'NumPad1',
  'NumPad2',
  'NumPad3',
  'NumPad4',
  'NumPad5',
  'NumPad6',
  'NumPad7',
  'NumPad8',
  'NumPad9',
  'CapsLock',
  'ScrollLock',
  'NumLock',
  'AudioMute',
  'AudioVolDown',
  'AudioVolUp',
  'MediaPlay',
  'MediaStop',
  'MediaPause',
  'MediaPrev',
  'MediaNext',
];

final _logicalKeyboardKeyNames = <LogicalKeyboardKey, String>{
  LogicalKeyboardKey.space: 'Space',
  LogicalKeyboardKey.escape: 'Escape',
  LogicalKeyboardKey.tab: 'Tab',
  LogicalKeyboardKey.altLeft: 'LeftAlt',
  LogicalKeyboardKey.altRight: 'RightAlt',
  LogicalKeyboardKey.controlLeft: 'LeftControl',
  LogicalKeyboardKey.controlRight: 'RightControl',
  LogicalKeyboardKey.shiftLeft: 'LeftShift',
  LogicalKeyboardKey.shiftRight: 'RightShift',
  LogicalKeyboardKey.f1: 'F1',
  LogicalKeyboardKey.f2: 'F2',
  LogicalKeyboardKey.f3: 'F3',
  LogicalKeyboardKey.f4: 'F4',
  LogicalKeyboardKey.f5: 'F5',
  LogicalKeyboardKey.f6: 'F6',
  LogicalKeyboardKey.f7: 'F7',
  LogicalKeyboardKey.f8: 'F8',
  LogicalKeyboardKey.f9: 'F9',
  LogicalKeyboardKey.f10: 'F10',
  LogicalKeyboardKey.f11: 'F11',
  LogicalKeyboardKey.f12: 'F12',
  LogicalKeyboardKey.f13: 'F13',
  LogicalKeyboardKey.f14: 'F14',
  LogicalKeyboardKey.f15: 'F15',
  LogicalKeyboardKey.f16: 'F16',
  LogicalKeyboardKey.f17: 'F17',
  LogicalKeyboardKey.f18: 'F18',
  LogicalKeyboardKey.f19: 'F19',
  LogicalKeyboardKey.f20: 'F20',
  LogicalKeyboardKey.f21: 'F21',
  LogicalKeyboardKey.f22: 'F22',
  LogicalKeyboardKey.f23: 'F23',
  LogicalKeyboardKey.f24: 'F24',
  LogicalKeyboardKey.digit0: '0',
  LogicalKeyboardKey.digit1: '1',
  LogicalKeyboardKey.digit2: '2',
  LogicalKeyboardKey.digit3: '3',
  LogicalKeyboardKey.digit4: '4',
  LogicalKeyboardKey.digit5: '5',
  LogicalKeyboardKey.digit6: '6',
  LogicalKeyboardKey.digit7: '7',
  LogicalKeyboardKey.digit8: '8',
  LogicalKeyboardKey.digit9: '9',
  LogicalKeyboardKey.keyA: 'A',
  LogicalKeyboardKey.keyB: 'B',
  LogicalKeyboardKey.keyC: 'C',
  LogicalKeyboardKey.keyD: 'D',
  LogicalKeyboardKey.keyE: 'E',
  LogicalKeyboardKey.keyF: 'F',
  LogicalKeyboardKey.keyG: 'G',
  LogicalKeyboardKey.keyH: 'H',
  LogicalKeyboardKey.keyI: 'I',
  LogicalKeyboardKey.keyJ: 'J',
  LogicalKeyboardKey.keyK: 'K',
  LogicalKeyboardKey.keyL: 'L',
  LogicalKeyboardKey.keyM: 'M',
  LogicalKeyboardKey.keyN: 'N',
  LogicalKeyboardKey.keyO: 'O',
  LogicalKeyboardKey.keyP: 'P',
  LogicalKeyboardKey.keyQ: 'Q',
  LogicalKeyboardKey.keyR: 'R',
  LogicalKeyboardKey.keyS: 'S',
  LogicalKeyboardKey.keyT: 'T',
  LogicalKeyboardKey.keyU: 'U',
  LogicalKeyboardKey.keyV: 'V',
  LogicalKeyboardKey.keyW: 'W',
  LogicalKeyboardKey.keyX: 'X',
  LogicalKeyboardKey.keyY: 'Y',
  LogicalKeyboardKey.keyZ: 'Z',
  LogicalKeyboardKey.minus: 'Minus',
  LogicalKeyboardKey.equal: 'Equals',
  LogicalKeyboardKey.backspace: 'Backspace',
  LogicalKeyboardKey.bracketLeft: 'LeftBracket',
  LogicalKeyboardKey.bracketRight: 'RightBracket',
  LogicalKeyboardKey.backslash: 'Backslash',
  LogicalKeyboardKey.semicolon: 'Semicolon',
  LogicalKeyboardKey.quote: 'Quote',
  LogicalKeyboardKey.enter: 'Enter',
  LogicalKeyboardKey.comma: 'Comma',
  LogicalKeyboardKey.period: 'Period',
  LogicalKeyboardKey.slash: 'Slash',
  LogicalKeyboardKey.arrowLeft: 'Left',
  LogicalKeyboardKey.arrowUp: 'Up',
  LogicalKeyboardKey.arrowRight: 'Right',
  LogicalKeyboardKey.arrowDown: 'Down',
  LogicalKeyboardKey.printScreen: 'PrintScreen',
  LogicalKeyboardKey.pause: 'Pause',
  LogicalKeyboardKey.insert: 'Insert',
  LogicalKeyboardKey.delete: 'Delete',
  LogicalKeyboardKey.home: 'Home',
  LogicalKeyboardKey.end: 'End',
  LogicalKeyboardKey.pageUp: 'PageUp',
  LogicalKeyboardKey.pageDown: 'PageDown',
  LogicalKeyboardKey.numpadAdd: 'Add',
  LogicalKeyboardKey.numpadSubtract: 'Subtract',
  LogicalKeyboardKey.numpadMultiply: 'Multiply',
  LogicalKeyboardKey.numpadDivide: 'Divide',
  LogicalKeyboardKey.numpadDecimal: 'Decimal',
  LogicalKeyboardKey.numpad0: 'NumPad0',
  LogicalKeyboardKey.numpad1: 'NumPad1',
  LogicalKeyboardKey.numpad2: 'NumPad2',
  LogicalKeyboardKey.numpad3: 'NumPad3',
  LogicalKeyboardKey.numpad4: 'NumPad4',
  LogicalKeyboardKey.numpad5: 'NumPad5',
  LogicalKeyboardKey.numpad6: 'NumPad6',
  LogicalKeyboardKey.numpad7: 'NumPad7',
  LogicalKeyboardKey.numpad8: 'NumPad8',
  LogicalKeyboardKey.numpad9: 'NumPad9',
  LogicalKeyboardKey.capsLock: 'CapsLock',
  LogicalKeyboardKey.scrollLock: 'ScrollLock',
  LogicalKeyboardKey.numLock: 'NumLock',
  LogicalKeyboardKey.audioVolumeMute: 'AudioMute',
  LogicalKeyboardKey.audioVolumeDown: 'AudioVolDown',
  LogicalKeyboardKey.audioVolumeUp: 'AudioVolUp',
  LogicalKeyboardKey.mediaPlayPause: 'MediaPlay',
  LogicalKeyboardKey.mediaStop: 'MediaStop',
  LogicalKeyboardKey.mediaTrackPrevious: 'MediaPrev',
  LogicalKeyboardKey.mediaTrackNext: 'MediaNext',
};

String? keyboardKeyNameForLogicalKey(LogicalKeyboardKey key) =>
    _logicalKeyboardKeyNames[key];

final legacyKeyboardVirtualKeyCodes = Map.unmodifiable(<String, int>{
  'Space': 0x20,
  'Escape': 0x1b,
  'Tab': 0x09,
  'LeftAlt': 0x12,
  'RightAlt': 0x12,
  'LeftControl': 0x11,
  'RightControl': 0x11,
  'LeftShift': 0x10,
  'RightShift': 0x10,
  for (var functionNumber = 1; functionNumber <= 24; functionNumber++)
    'F$functionNumber': 0x6f + functionNumber,
  for (var digit = 0; digit <= 9; digit++) '$digit': 0x30 + digit,
  for (var letterCode = 0; letterCode < 26; letterCode++)
    String.fromCharCode(0x41 + letterCode): 0x41 + letterCode,
  'Minus': 0xbb,
  'Equals': 0xbb,
  'Backspace': 0x08,
  'LeftBracket': 0xdb,
  'RightBracket': 0xdd,
  'Backslash': 0xdc,
  'Semicolon': 0xba,
  'Quote': 0xde,
  'Enter': 0x0d,
  'Comma': 0xbc,
  'Period': 0xbe,
  'Slash': 0xbf,
  'Left': 0x25,
  'Up': 0x26,
  'Right': 0x27,
  'Down': 0x28,
  'PrintScreen': 0x2c,
  'Pause': 0x13,
  'Insert': 0x2d,
  'Delete': 0x2e,
  'Home': 0x24,
  'End': 0x23,
  'PageUp': 0x21,
  'PageDown': 0x22,
  'Add': 0x6b,
  'Subtract': 0x6d,
  'Multiply': 0x6a,
  'Divide': 0x6f,
  'Decimal': 0x6e,
  for (var number = 0; number <= 9; number++)
    'NumPad$number': 0x60 + number,
  'CapsLock': 0x14,
  'ScrollLock': 0x91,
  'NumLock': 0x90,
  'AudioMute': 0xad,
  'AudioVolDown': 0xae,
  'AudioVolUp': 0xaf,
  'MediaPlay': 0xb3,
  'MediaStop': 0xb2,
  'MediaPause': 0xb3,
  'MediaPrev': 0xb1,
  'MediaNext': 0xb0,
});

final _legacyKeyboardNamesByVirtualKey = _buildVirtualKeyNames();

int? virtualKeyCodeForKeyboardKey(String key) =>
    legacyKeyboardVirtualKeyCodes[key];

String? keyboardKeyNameForVirtualKey(int virtualKeyCode) =>
    _legacyKeyboardNamesByVirtualKey[virtualKeyCode];

String normalizeKeyboardKey(String key) {
  if (key.startsWith('Right')) return 'Left${key.substring(5)}';
  return key;
}

String keyboardKeyDisplayName(String key) {
  if (key.startsWith('Left')) return key.substring(4);
  if (key.startsWith('Right')) return key.substring(5);
  return key;
}

List<String> appendKeyboardKey(List<String> combo, String key) {
  final normalizedCombo = combo.map(normalizeKeyboardKey).toList();
  final normalizedKey = normalizeKeyboardKey(key);
  if (normalizedCombo.contains(normalizedKey)) return normalizedCombo;
  final next = [...normalizedCombo, normalizedKey];
  next.sort((left, right) {
    final priority = _keyboardKeyPriority(right).compareTo(
      _keyboardKeyPriority(left),
    );
    return priority == 0 ? left.compareTo(right) : priority;
  });
  return next;
}

String keyboardComboDisplayName(Iterable<String> combo) => combo
    .map(keyboardKeyDisplayName)
    .join(' + ');

int _keyboardKeyPriority(String key) => switch (normalizeKeyboardKey(key)) {
  'LeftControl' => 4,
  'LeftAlt' => 3,
  'LeftShift' => 2,
  _ => 1,
};

Map<int, String> _buildVirtualKeyNames() {
  final names = <int, String>{};
  for (final entry in legacyKeyboardVirtualKeyCodes.entries) {
    names.putIfAbsent(entry.value, () => entry.key);
  }
  return Map.unmodifiable(names);
}